# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'xan.ui'
#
# Created by: PyQt5 UI code generator 5.7
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_XAn(object):
    def setupUi(self, XAn):
        XAn.setObjectName("XAn")
        XAn.resize(1920, 950)
        self.centralWidget = QtWidgets.QWidget(XAn)
        self.centralWidget.setObjectName("centralWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralWidget)
        self.verticalLayout.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout.setSpacing(6)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tabWidget = QtWidgets.QTabWidget(self.centralWidget)
        self.tabWidget.setObjectName("tabWidget")
        self.tab_plots_monitoring = QtWidgets.QWidget()
        self.tab_plots_monitoring.setObjectName("tab_plots_monitoring")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.tab_plots_monitoring)
        self.verticalLayout_2.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout_2.setSpacing(6)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setContentsMargins(11, 11, 11, 11)
        self.gridLayout.setSpacing(6)
        self.gridLayout.setObjectName("gridLayout")
        self.groupBox_6 = QtWidgets.QGroupBox(self.tab_plots_monitoring)
        self.groupBox_6.setObjectName("groupBox_6")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.groupBox_6)
        self.verticalLayout_11.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout_11.setSpacing(6)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.gridLayout_7 = QtWidgets.QGridLayout()
        self.gridLayout_7.setContentsMargins(11, 11, 11, 11)
        self.gridLayout_7.setSpacing(6)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.comboBox_plot_5_x = QtWidgets.QComboBox(self.groupBox_6)
        self.comboBox_plot_5_x.setObjectName("comboBox_plot_5_x")
        self.comboBox_plot_5_x.addItem("")
        self.comboBox_plot_5_x.addItem("")
        self.comboBox_plot_5_x.addItem("")
        self.comboBox_plot_5_x.addItem("")
        self.comboBox_plot_5_x.addItem("")
        self.comboBox_plot_5_x.addItem("")
        self.comboBox_plot_5_x.addItem("")
        self.comboBox_plot_5_x.addItem("")
        self.comboBox_plot_5_x.addItem("")
        self.comboBox_plot_5_x.addItem("")
        self.comboBox_plot_5_x.addItem("")
        self.comboBox_plot_5_x.addItem("")
        self.comboBox_plot_5_x.addItem("")
        self.comboBox_plot_5_x.addItem("")
        self.comboBox_plot_5_x.addItem("")
        self.comboBox_plot_5_x.addItem("")
        self.comboBox_plot_5_x.addItem("")
        self.comboBox_plot_5_x.addItem("")
        self.comboBox_plot_5_x.addItem("")
        self.comboBox_plot_5_x.addItem("")
        self.comboBox_plot_5_x.addItem("")
        self.comboBox_plot_5_x.addItem("")
        self.comboBox_plot_5_x.addItem("")
        self.gridLayout_7.addWidget(self.comboBox_plot_5_x, 2, 1, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(40, 1, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_7.addItem(spacerItem, 1, 3, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 1, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_7.addItem(spacerItem1, 1, 1, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(40, 1, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_7.addItem(spacerItem2, 1, 2, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(40, 1, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_7.addItem(spacerItem3, 1, 4, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(1, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_7.addItem(spacerItem4, 0, 0, 1, 1)
        self.comboBox_plot_5_y = QtWidgets.QComboBox(self.groupBox_6)
        self.comboBox_plot_5_y.setObjectName("comboBox_plot_5_y")
        self.comboBox_plot_5_y.addItem("")
        self.comboBox_plot_5_y.addItem("")
        self.comboBox_plot_5_y.addItem("")
        self.comboBox_plot_5_y.addItem("")
        self.comboBox_plot_5_y.addItem("")
        self.comboBox_plot_5_y.addItem("")
        self.comboBox_plot_5_y.addItem("")
        self.comboBox_plot_5_y.addItem("")
        self.comboBox_plot_5_y.addItem("")
        self.comboBox_plot_5_y.addItem("")
        self.comboBox_plot_5_y.addItem("")
        self.comboBox_plot_5_y.addItem("")
        self.comboBox_plot_5_y.addItem("")
        self.comboBox_plot_5_y.addItem("")
        self.comboBox_plot_5_y.addItem("")
        self.comboBox_plot_5_y.addItem("")
        self.comboBox_plot_5_y.addItem("")
        self.comboBox_plot_5_y.addItem("")
        self.comboBox_plot_5_y.addItem("")
        self.comboBox_plot_5_y.addItem("")
        self.comboBox_plot_5_y.addItem("")
        self.comboBox_plot_5_y.addItem("")
        self.comboBox_plot_5_y.addItem("")
        self.gridLayout_7.addWidget(self.comboBox_plot_5_y, 2, 2, 1, 1)
        spacerItem5 = QtWidgets.QSpacerItem(40, 1, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_7.addItem(spacerItem5, 1, 5, 1, 1)
        self.verticalLayout_mon_05 = QtWidgets.QVBoxLayout()
        self.verticalLayout_mon_05.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout_mon_05.setSpacing(6)
        self.verticalLayout_mon_05.setObjectName("verticalLayout_mon_05")
        self.gridLayout_7.addLayout(self.verticalLayout_mon_05, 0, 1, 1, 5)
        self.pushButton_plot_mon_05 = QtWidgets.QPushButton(self.groupBox_6)
        self.pushButton_plot_mon_05.setObjectName("pushButton_plot_mon_05")
        self.gridLayout_7.addWidget(self.pushButton_plot_mon_05, 2, 5, 1, 1)
        self.pushButton_plot_mon_05_clear = QtWidgets.QPushButton(self.groupBox_6)
        self.pushButton_plot_mon_05_clear.setObjectName("pushButton_plot_mon_05_clear")
        self.gridLayout_7.addWidget(self.pushButton_plot_mon_05_clear, 2, 4, 1, 1)
        self.verticalLayout_11.addLayout(self.gridLayout_7)
        self.gridLayout.addWidget(self.groupBox_6, 3, 0, 1, 1)
        self.groupBox_3 = QtWidgets.QGroupBox(self.tab_plots_monitoring)
        self.groupBox_3.setObjectName("groupBox_3")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.groupBox_3)
        self.verticalLayout_8.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout_8.setSpacing(6)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.gridLayout_4 = QtWidgets.QGridLayout()
        self.gridLayout_4.setContentsMargins(11, 11, 11, 11)
        self.gridLayout_4.setSpacing(6)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.comboBox_plot_2_x = QtWidgets.QComboBox(self.groupBox_3)
        self.comboBox_plot_2_x.setObjectName("comboBox_plot_2_x")
        self.comboBox_plot_2_x.addItem("")
        self.comboBox_plot_2_x.addItem("")
        self.comboBox_plot_2_x.addItem("")
        self.comboBox_plot_2_x.addItem("")
        self.comboBox_plot_2_x.addItem("")
        self.comboBox_plot_2_x.addItem("")
        self.comboBox_plot_2_x.addItem("")
        self.comboBox_plot_2_x.addItem("")
        self.comboBox_plot_2_x.addItem("")
        self.comboBox_plot_2_x.addItem("")
        self.comboBox_plot_2_x.addItem("")
        self.comboBox_plot_2_x.addItem("")
        self.comboBox_plot_2_x.addItem("")
        self.comboBox_plot_2_x.addItem("")
        self.comboBox_plot_2_x.addItem("")
        self.comboBox_plot_2_x.addItem("")
        self.comboBox_plot_2_x.addItem("")
        self.comboBox_plot_2_x.addItem("")
        self.comboBox_plot_2_x.addItem("")
        self.comboBox_plot_2_x.addItem("")
        self.comboBox_plot_2_x.addItem("")
        self.comboBox_plot_2_x.addItem("")
        self.comboBox_plot_2_x.addItem("")
        self.gridLayout_4.addWidget(self.comboBox_plot_2_x, 2, 1, 1, 1)
        spacerItem6 = QtWidgets.QSpacerItem(40, 1, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem6, 1, 2, 1, 1)
        spacerItem7 = QtWidgets.QSpacerItem(40, 1, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem7, 1, 3, 1, 1)
        spacerItem8 = QtWidgets.QSpacerItem(40, 1, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem8, 1, 4, 1, 1)
        spacerItem9 = QtWidgets.QSpacerItem(40, 1, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem9, 1, 1, 1, 1)
        spacerItem10 = QtWidgets.QSpacerItem(1, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_4.addItem(spacerItem10, 0, 0, 1, 1)
        self.comboBox_plot_2_y = QtWidgets.QComboBox(self.groupBox_3)
        self.comboBox_plot_2_y.setObjectName("comboBox_plot_2_y")
        self.comboBox_plot_2_y.addItem("")
        self.comboBox_plot_2_y.addItem("")
        self.comboBox_plot_2_y.addItem("")
        self.comboBox_plot_2_y.addItem("")
        self.comboBox_plot_2_y.addItem("")
        self.comboBox_plot_2_y.addItem("")
        self.comboBox_plot_2_y.addItem("")
        self.comboBox_plot_2_y.addItem("")
        self.comboBox_plot_2_y.addItem("")
        self.comboBox_plot_2_y.addItem("")
        self.comboBox_plot_2_y.addItem("")
        self.comboBox_plot_2_y.addItem("")
        self.comboBox_plot_2_y.addItem("")
        self.comboBox_plot_2_y.addItem("")
        self.comboBox_plot_2_y.addItem("")
        self.comboBox_plot_2_y.addItem("")
        self.comboBox_plot_2_y.addItem("")
        self.comboBox_plot_2_y.addItem("")
        self.comboBox_plot_2_y.addItem("")
        self.comboBox_plot_2_y.addItem("")
        self.comboBox_plot_2_y.addItem("")
        self.comboBox_plot_2_y.addItem("")
        self.comboBox_plot_2_y.addItem("")
        self.gridLayout_4.addWidget(self.comboBox_plot_2_y, 2, 2, 1, 1)
        spacerItem11 = QtWidgets.QSpacerItem(40, 1, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem11, 1, 5, 1, 1)
        self.verticalLayout_mon_02 = QtWidgets.QVBoxLayout()
        self.verticalLayout_mon_02.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout_mon_02.setSpacing(6)
        self.verticalLayout_mon_02.setObjectName("verticalLayout_mon_02")
        self.gridLayout_4.addLayout(self.verticalLayout_mon_02, 0, 1, 1, 5)
        self.pushButton_plot_mon_02 = QtWidgets.QPushButton(self.groupBox_3)
        self.pushButton_plot_mon_02.setObjectName("pushButton_plot_mon_02")
        self.gridLayout_4.addWidget(self.pushButton_plot_mon_02, 2, 5, 1, 1)
        self.pushButton_plot_mon_02_clear = QtWidgets.QPushButton(self.groupBox_3)
        self.pushButton_plot_mon_02_clear.setObjectName("pushButton_plot_mon_02_clear")
        self.gridLayout_4.addWidget(self.pushButton_plot_mon_02_clear, 2, 4, 1, 1)
        self.verticalLayout_8.addLayout(self.gridLayout_4)
        self.gridLayout.addWidget(self.groupBox_3, 1, 1, 1, 1)
        self.groupBox_7 = QtWidgets.QGroupBox(self.tab_plots_monitoring)
        self.groupBox_7.setObjectName("groupBox_7")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(self.groupBox_7)
        self.verticalLayout_12.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout_12.setSpacing(6)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.gridLayout_14 = QtWidgets.QGridLayout()
        self.gridLayout_14.setContentsMargins(11, 11, 11, 11)
        self.gridLayout_14.setSpacing(6)
        self.gridLayout_14.setObjectName("gridLayout_14")
        spacerItem12 = QtWidgets.QSpacerItem(40, 1, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_14.addItem(spacerItem12, 1, 1, 1, 1)
        spacerItem13 = QtWidgets.QSpacerItem(1, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_14.addItem(spacerItem13, 0, 0, 1, 1)
        self.comboBox_plot_6_y = QtWidgets.QComboBox(self.groupBox_7)
        self.comboBox_plot_6_y.setObjectName("comboBox_plot_6_y")
        self.comboBox_plot_6_y.addItem("")
        self.comboBox_plot_6_y.addItem("")
        self.comboBox_plot_6_y.addItem("")
        self.comboBox_plot_6_y.addItem("")
        self.comboBox_plot_6_y.addItem("")
        self.comboBox_plot_6_y.addItem("")
        self.comboBox_plot_6_y.addItem("")
        self.comboBox_plot_6_y.addItem("")
        self.comboBox_plot_6_y.addItem("")
        self.comboBox_plot_6_y.addItem("")
        self.comboBox_plot_6_y.addItem("")
        self.comboBox_plot_6_y.addItem("")
        self.comboBox_plot_6_y.addItem("")
        self.comboBox_plot_6_y.addItem("")
        self.comboBox_plot_6_y.addItem("")
        self.comboBox_plot_6_y.addItem("")
        self.comboBox_plot_6_y.addItem("")
        self.comboBox_plot_6_y.addItem("")
        self.comboBox_plot_6_y.addItem("")
        self.comboBox_plot_6_y.addItem("")
        self.comboBox_plot_6_y.addItem("")
        self.comboBox_plot_6_y.addItem("")
        self.comboBox_plot_6_y.addItem("")
        self.gridLayout_14.addWidget(self.comboBox_plot_6_y, 2, 2, 1, 1)
        self.comboBox_plot_6_x = QtWidgets.QComboBox(self.groupBox_7)
        self.comboBox_plot_6_x.setObjectName("comboBox_plot_6_x")
        self.comboBox_plot_6_x.addItem("")
        self.comboBox_plot_6_x.addItem("")
        self.comboBox_plot_6_x.addItem("")
        self.comboBox_plot_6_x.addItem("")
        self.comboBox_plot_6_x.addItem("")
        self.comboBox_plot_6_x.addItem("")
        self.comboBox_plot_6_x.addItem("")
        self.comboBox_plot_6_x.addItem("")
        self.comboBox_plot_6_x.addItem("")
        self.comboBox_plot_6_x.addItem("")
        self.comboBox_plot_6_x.addItem("")
        self.comboBox_plot_6_x.addItem("")
        self.comboBox_plot_6_x.addItem("")
        self.comboBox_plot_6_x.addItem("")
        self.comboBox_plot_6_x.addItem("")
        self.comboBox_plot_6_x.addItem("")
        self.comboBox_plot_6_x.addItem("")
        self.comboBox_plot_6_x.addItem("")
        self.comboBox_plot_6_x.addItem("")
        self.comboBox_plot_6_x.addItem("")
        self.comboBox_plot_6_x.addItem("")
        self.comboBox_plot_6_x.addItem("")
        self.comboBox_plot_6_x.addItem("")
        self.gridLayout_14.addWidget(self.comboBox_plot_6_x, 2, 1, 1, 1)
        spacerItem14 = QtWidgets.QSpacerItem(40, 1, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_14.addItem(spacerItem14, 1, 4, 1, 1)
        spacerItem15 = QtWidgets.QSpacerItem(40, 1, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_14.addItem(spacerItem15, 1, 2, 1, 1)
        spacerItem16 = QtWidgets.QSpacerItem(40, 1, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_14.addItem(spacerItem16, 1, 3, 1, 1)
        spacerItem17 = QtWidgets.QSpacerItem(40, 1, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_14.addItem(spacerItem17, 1, 5, 1, 1)
        self.verticalLayout_mon_06 = QtWidgets.QVBoxLayout()
        self.verticalLayout_mon_06.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout_mon_06.setSpacing(6)
        self.verticalLayout_mon_06.setObjectName("verticalLayout_mon_06")
        self.gridLayout_14.addLayout(self.verticalLayout_mon_06, 0, 1, 1, 5)
        self.pushButton_plot_mon_06 = QtWidgets.QPushButton(self.groupBox_7)
        self.pushButton_plot_mon_06.setObjectName("pushButton_plot_mon_06")
        self.gridLayout_14.addWidget(self.pushButton_plot_mon_06, 2, 5, 1, 1)
        self.pushButton_plot_mon_06_clear = QtWidgets.QPushButton(self.groupBox_7)
        self.pushButton_plot_mon_06_clear.setObjectName("pushButton_plot_mon_06_clear")
        self.gridLayout_14.addWidget(self.pushButton_plot_mon_06_clear, 2, 4, 1, 1)
        self.verticalLayout_12.addLayout(self.gridLayout_14)
        self.gridLayout.addWidget(self.groupBox_7, 3, 1, 1, 1)
        self.groupBox_5 = QtWidgets.QGroupBox(self.tab_plots_monitoring)
        self.groupBox_5.setObjectName("groupBox_5")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.groupBox_5)
        self.verticalLayout_10.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout_10.setSpacing(6)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.gridLayout_6 = QtWidgets.QGridLayout()
        self.gridLayout_6.setContentsMargins(11, 11, 11, 11)
        self.gridLayout_6.setSpacing(6)
        self.gridLayout_6.setObjectName("gridLayout_6")
        spacerItem18 = QtWidgets.QSpacerItem(40, 1, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_6.addItem(spacerItem18, 1, 3, 1, 1)
        self.comboBox_plot_4_x = QtWidgets.QComboBox(self.groupBox_5)
        self.comboBox_plot_4_x.setObjectName("comboBox_plot_4_x")
        self.comboBox_plot_4_x.addItem("")
        self.comboBox_plot_4_x.addItem("")
        self.comboBox_plot_4_x.addItem("")
        self.comboBox_plot_4_x.addItem("")
        self.comboBox_plot_4_x.addItem("")
        self.comboBox_plot_4_x.addItem("")
        self.comboBox_plot_4_x.addItem("")
        self.comboBox_plot_4_x.addItem("")
        self.comboBox_plot_4_x.addItem("")
        self.comboBox_plot_4_x.addItem("")
        self.comboBox_plot_4_x.addItem("")
        self.comboBox_plot_4_x.addItem("")
        self.comboBox_plot_4_x.addItem("")
        self.comboBox_plot_4_x.addItem("")
        self.comboBox_plot_4_x.addItem("")
        self.comboBox_plot_4_x.addItem("")
        self.comboBox_plot_4_x.addItem("")
        self.comboBox_plot_4_x.addItem("")
        self.comboBox_plot_4_x.addItem("")
        self.comboBox_plot_4_x.addItem("")
        self.comboBox_plot_4_x.addItem("")
        self.comboBox_plot_4_x.addItem("")
        self.comboBox_plot_4_x.addItem("")
        self.gridLayout_6.addWidget(self.comboBox_plot_4_x, 2, 1, 1, 1)
        self.comboBox_plot_4_y = QtWidgets.QComboBox(self.groupBox_5)
        self.comboBox_plot_4_y.setObjectName("comboBox_plot_4_y")
        self.comboBox_plot_4_y.addItem("")
        self.comboBox_plot_4_y.addItem("")
        self.comboBox_plot_4_y.addItem("")
        self.comboBox_plot_4_y.addItem("")
        self.comboBox_plot_4_y.addItem("")
        self.comboBox_plot_4_y.addItem("")
        self.comboBox_plot_4_y.addItem("")
        self.comboBox_plot_4_y.addItem("")
        self.comboBox_plot_4_y.addItem("")
        self.comboBox_plot_4_y.addItem("")
        self.comboBox_plot_4_y.addItem("")
        self.comboBox_plot_4_y.addItem("")
        self.comboBox_plot_4_y.addItem("")
        self.comboBox_plot_4_y.addItem("")
        self.comboBox_plot_4_y.addItem("")
        self.comboBox_plot_4_y.addItem("")
        self.comboBox_plot_4_y.addItem("")
        self.comboBox_plot_4_y.addItem("")
        self.comboBox_plot_4_y.addItem("")
        self.comboBox_plot_4_y.addItem("")
        self.comboBox_plot_4_y.addItem("")
        self.comboBox_plot_4_y.addItem("")
        self.comboBox_plot_4_y.addItem("")
        self.gridLayout_6.addWidget(self.comboBox_plot_4_y, 2, 2, 1, 1)
        spacerItem19 = QtWidgets.QSpacerItem(40, 1, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_6.addItem(spacerItem19, 1, 2, 1, 1)
        spacerItem20 = QtWidgets.QSpacerItem(40, 1, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_6.addItem(spacerItem20, 1, 4, 1, 1)
        spacerItem21 = QtWidgets.QSpacerItem(1, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_6.addItem(spacerItem21, 0, 0, 1, 1)
        spacerItem22 = QtWidgets.QSpacerItem(40, 1, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_6.addItem(spacerItem22, 1, 1, 1, 1)
        spacerItem23 = QtWidgets.QSpacerItem(40, 1, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_6.addItem(spacerItem23, 1, 5, 1, 1)
        self.verticalLayout_mon_04 = QtWidgets.QVBoxLayout()
        self.verticalLayout_mon_04.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout_mon_04.setSpacing(6)
        self.verticalLayout_mon_04.setObjectName("verticalLayout_mon_04")
        self.gridLayout_6.addLayout(self.verticalLayout_mon_04, 0, 1, 1, 5)
        self.pushButton_plot_mon_04 = QtWidgets.QPushButton(self.groupBox_5)
        self.pushButton_plot_mon_04.setObjectName("pushButton_plot_mon_04")
        self.gridLayout_6.addWidget(self.pushButton_plot_mon_04, 2, 5, 1, 1)
        self.pushButton_plot_mon_04_clear = QtWidgets.QPushButton(self.groupBox_5)
        self.pushButton_plot_mon_04_clear.setObjectName("pushButton_plot_mon_04_clear")
        self.gridLayout_6.addWidget(self.pushButton_plot_mon_04_clear, 2, 4, 1, 1)
        self.verticalLayout_10.addLayout(self.gridLayout_6)
        self.gridLayout.addWidget(self.groupBox_5, 2, 1, 1, 1)
        self.groupBox_8 = QtWidgets.QGroupBox(self.tab_plots_monitoring)
        self.groupBox_8.setObjectName("groupBox_8")
        self.verticalLayout_16 = QtWidgets.QVBoxLayout(self.groupBox_8)
        self.verticalLayout_16.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout_16.setSpacing(6)
        self.verticalLayout_16.setObjectName("verticalLayout_16")
        self.gridLayout_15 = QtWidgets.QGridLayout()
        self.gridLayout_15.setContentsMargins(11, 11, 11, 11)
        self.gridLayout_15.setSpacing(6)
        self.gridLayout_15.setObjectName("gridLayout_15")
        spacerItem24 = QtWidgets.QSpacerItem(40, 1, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_15.addItem(spacerItem24, 0, 2, 1, 1)
        spacerItem25 = QtWidgets.QSpacerItem(40, 1, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_15.addItem(spacerItem25, 0, 3, 1, 1)
        spacerItem26 = QtWidgets.QSpacerItem(40, 1, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_15.addItem(spacerItem26, 0, 1, 1, 1)
        spacerItem27 = QtWidgets.QSpacerItem(40, 1, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_15.addItem(spacerItem27, 0, 0, 1, 1)
        self.pushButton_plot_mon_all = QtWidgets.QPushButton(self.groupBox_8)
        self.pushButton_plot_mon_all.setObjectName("pushButton_plot_mon_all")
        self.gridLayout_15.addWidget(self.pushButton_plot_mon_all, 1, 3, 1, 1)
        self.pushButton_plot_mon_clear_all = QtWidgets.QPushButton(self.groupBox_8)
        self.pushButton_plot_mon_clear_all.setObjectName("pushButton_plot_mon_clear_all")
        self.gridLayout_15.addWidget(self.pushButton_plot_mon_clear_all, 1, 2, 1, 1)
        self.verticalLayout_16.addLayout(self.gridLayout_15)
        self.gridLayout.addWidget(self.groupBox_8, 4, 0, 1, 2)
        self.groupBox = QtWidgets.QGroupBox(self.tab_plots_monitoring)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout_3.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout_3.setSpacing(6)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setContentsMargins(11, 11, 11, 11)
        self.gridLayout_2.setSpacing(6)
        self.gridLayout_2.setObjectName("gridLayout_2")
        spacerItem28 = QtWidgets.QSpacerItem(40, 1, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem28, 0, 1, 1, 1)
        self.lineEdit_monitoring_load_data = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_monitoring_load_data.setObjectName("lineEdit_monitoring_load_data")
        self.gridLayout_2.addWidget(self.lineEdit_monitoring_load_data, 1, 1, 1, 2)
        spacerItem29 = QtWidgets.QSpacerItem(40, 1, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem29, 0, 3, 1, 1)
        spacerItem30 = QtWidgets.QSpacerItem(40, 1, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem30, 0, 2, 1, 1)
        self.pushButton_monitoring_browse_data = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_monitoring_browse_data.setObjectName("pushButton_monitoring_browse_data")
        self.gridLayout_2.addWidget(self.pushButton_monitoring_browse_data, 1, 0, 1, 1)
        spacerItem31 = QtWidgets.QSpacerItem(40, 1, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem31, 0, 0, 1, 1)
        self.pushButton_monitoring_load_data = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_monitoring_load_data.setObjectName("pushButton_monitoring_load_data")
        self.gridLayout_2.addWidget(self.pushButton_monitoring_load_data, 1, 3, 1, 1)
        self.verticalLayout_3.addLayout(self.gridLayout_2)
        self.gridLayout.addWidget(self.groupBox, 0, 0, 1, 2)
        self.groupBox_2 = QtWidgets.QGroupBox(self.tab_plots_monitoring)
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_7.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout_7.setSpacing(6)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setContentsMargins(11, 11, 11, 11)
        self.gridLayout_3.setSpacing(6)
        self.gridLayout_3.setObjectName("gridLayout_3")
        spacerItem32 = QtWidgets.QSpacerItem(40, 1, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem32, 1, 2, 1, 1)
        self.comboBox_plot_1_y = QtWidgets.QComboBox(self.groupBox_2)
        self.comboBox_plot_1_y.setObjectName("comboBox_plot_1_y")
        self.comboBox_plot_1_y.addItem("")
        self.comboBox_plot_1_y.addItem("")
        self.comboBox_plot_1_y.addItem("")
        self.comboBox_plot_1_y.addItem("")
        self.comboBox_plot_1_y.addItem("")
        self.comboBox_plot_1_y.addItem("")
        self.comboBox_plot_1_y.addItem("")
        self.comboBox_plot_1_y.addItem("")
        self.comboBox_plot_1_y.addItem("")
        self.comboBox_plot_1_y.addItem("")
        self.comboBox_plot_1_y.addItem("")
        self.comboBox_plot_1_y.addItem("")
        self.comboBox_plot_1_y.addItem("")
        self.comboBox_plot_1_y.addItem("")
        self.comboBox_plot_1_y.addItem("")
        self.comboBox_plot_1_y.addItem("")
        self.comboBox_plot_1_y.addItem("")
        self.comboBox_plot_1_y.addItem("")
        self.comboBox_plot_1_y.addItem("")
        self.comboBox_plot_1_y.addItem("")
        self.comboBox_plot_1_y.addItem("")
        self.comboBox_plot_1_y.addItem("")
        self.comboBox_plot_1_y.addItem("")
        self.gridLayout_3.addWidget(self.comboBox_plot_1_y, 2, 2, 1, 1)
        spacerItem33 = QtWidgets.QSpacerItem(40, 1, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem33, 1, 4, 1, 1)
        spacerItem34 = QtWidgets.QSpacerItem(40, 1, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem34, 1, 1, 1, 1)
        spacerItem35 = QtWidgets.QSpacerItem(40, 1, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem35, 1, 3, 1, 1)
        spacerItem36 = QtWidgets.QSpacerItem(1, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_3.addItem(spacerItem36, 0, 0, 1, 1)
        self.comboBox_plot_1_x = QtWidgets.QComboBox(self.groupBox_2)
        self.comboBox_plot_1_x.setObjectName("comboBox_plot_1_x")
        self.comboBox_plot_1_x.addItem("")
        self.comboBox_plot_1_x.addItem("")
        self.comboBox_plot_1_x.addItem("")
        self.comboBox_plot_1_x.addItem("")
        self.comboBox_plot_1_x.addItem("")
        self.comboBox_plot_1_x.addItem("")
        self.comboBox_plot_1_x.addItem("")
        self.comboBox_plot_1_x.addItem("")
        self.comboBox_plot_1_x.addItem("")
        self.comboBox_plot_1_x.addItem("")
        self.comboBox_plot_1_x.addItem("")
        self.comboBox_plot_1_x.addItem("")
        self.comboBox_plot_1_x.addItem("")
        self.comboBox_plot_1_x.addItem("")
        self.comboBox_plot_1_x.addItem("")
        self.comboBox_plot_1_x.addItem("")
        self.comboBox_plot_1_x.addItem("")
        self.comboBox_plot_1_x.addItem("")
        self.comboBox_plot_1_x.addItem("")
        self.comboBox_plot_1_x.addItem("")
        self.comboBox_plot_1_x.addItem("")
        self.comboBox_plot_1_x.addItem("")
        self.comboBox_plot_1_x.addItem("")
        self.gridLayout_3.addWidget(self.comboBox_plot_1_x, 2, 1, 1, 1)
        self.verticalLayout_mon_01 = QtWidgets.QVBoxLayout()
        self.verticalLayout_mon_01.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout_mon_01.setSpacing(6)
        self.verticalLayout_mon_01.setObjectName("verticalLayout_mon_01")
        self.gridLayout_3.addLayout(self.verticalLayout_mon_01, 0, 1, 1, 5)
        spacerItem37 = QtWidgets.QSpacerItem(40, 1, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem37, 1, 5, 1, 1)
        self.pushButton_plot_mon_01 = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButton_plot_mon_01.setObjectName("pushButton_plot_mon_01")
        self.gridLayout_3.addWidget(self.pushButton_plot_mon_01, 2, 5, 1, 1)
        self.pushButton_plot_mon_01_clear = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButton_plot_mon_01_clear.setObjectName("pushButton_plot_mon_01_clear")
        self.gridLayout_3.addWidget(self.pushButton_plot_mon_01_clear, 2, 4, 1, 1)
        self.verticalLayout_7.addLayout(self.gridLayout_3)
        self.gridLayout.addWidget(self.groupBox_2, 1, 0, 1, 1)
        self.groupBox_4 = QtWidgets.QGroupBox(self.tab_plots_monitoring)
        self.groupBox_4.setObjectName("groupBox_4")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.groupBox_4)
        self.verticalLayout_9.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout_9.setSpacing(6)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.gridLayout_5 = QtWidgets.QGridLayout()
        self.gridLayout_5.setContentsMargins(11, 11, 11, 11)
        self.gridLayout_5.setSpacing(6)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.comboBox_plot_3_x = QtWidgets.QComboBox(self.groupBox_4)
        self.comboBox_plot_3_x.setObjectName("comboBox_plot_3_x")
        self.comboBox_plot_3_x.addItem("")
        self.comboBox_plot_3_x.addItem("")
        self.comboBox_plot_3_x.addItem("")
        self.comboBox_plot_3_x.addItem("")
        self.comboBox_plot_3_x.addItem("")
        self.comboBox_plot_3_x.addItem("")
        self.comboBox_plot_3_x.addItem("")
        self.comboBox_plot_3_x.addItem("")
        self.comboBox_plot_3_x.addItem("")
        self.comboBox_plot_3_x.addItem("")
        self.comboBox_plot_3_x.addItem("")
        self.comboBox_plot_3_x.addItem("")
        self.comboBox_plot_3_x.addItem("")
        self.comboBox_plot_3_x.addItem("")
        self.comboBox_plot_3_x.addItem("")
        self.comboBox_plot_3_x.addItem("")
        self.comboBox_plot_3_x.addItem("")
        self.comboBox_plot_3_x.addItem("")
        self.comboBox_plot_3_x.addItem("")
        self.comboBox_plot_3_x.addItem("")
        self.comboBox_plot_3_x.addItem("")
        self.comboBox_plot_3_x.addItem("")
        self.comboBox_plot_3_x.addItem("")
        self.gridLayout_5.addWidget(self.comboBox_plot_3_x, 2, 1, 1, 1)
        self.comboBox_plot_3_y = QtWidgets.QComboBox(self.groupBox_4)
        self.comboBox_plot_3_y.setObjectName("comboBox_plot_3_y")
        self.comboBox_plot_3_y.addItem("")
        self.comboBox_plot_3_y.addItem("")
        self.comboBox_plot_3_y.addItem("")
        self.comboBox_plot_3_y.addItem("")
        self.comboBox_plot_3_y.addItem("")
        self.comboBox_plot_3_y.addItem("")
        self.comboBox_plot_3_y.addItem("")
        self.comboBox_plot_3_y.addItem("")
        self.comboBox_plot_3_y.addItem("")
        self.comboBox_plot_3_y.addItem("")
        self.comboBox_plot_3_y.addItem("")
        self.comboBox_plot_3_y.addItem("")
        self.comboBox_plot_3_y.addItem("")
        self.comboBox_plot_3_y.addItem("")
        self.comboBox_plot_3_y.addItem("")
        self.comboBox_plot_3_y.addItem("")
        self.comboBox_plot_3_y.addItem("")
        self.comboBox_plot_3_y.addItem("")
        self.comboBox_plot_3_y.addItem("")
        self.comboBox_plot_3_y.addItem("")
        self.comboBox_plot_3_y.addItem("")
        self.comboBox_plot_3_y.addItem("")
        self.comboBox_plot_3_y.addItem("")
        self.gridLayout_5.addWidget(self.comboBox_plot_3_y, 2, 2, 1, 1)
        spacerItem38 = QtWidgets.QSpacerItem(1, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_5.addItem(spacerItem38, 0, 0, 1, 1)
        spacerItem39 = QtWidgets.QSpacerItem(40, 1, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_5.addItem(spacerItem39, 1, 2, 1, 1)
        spacerItem40 = QtWidgets.QSpacerItem(40, 1, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_5.addItem(spacerItem40, 1, 1, 1, 1)
        spacerItem41 = QtWidgets.QSpacerItem(40, 1, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_5.addItem(spacerItem41, 1, 3, 1, 1)
        spacerItem42 = QtWidgets.QSpacerItem(40, 1, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_5.addItem(spacerItem42, 1, 4, 1, 1)
        spacerItem43 = QtWidgets.QSpacerItem(40, 1, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_5.addItem(spacerItem43, 1, 5, 1, 1)
        self.verticalLayout_mon_03 = QtWidgets.QVBoxLayout()
        self.verticalLayout_mon_03.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout_mon_03.setSpacing(6)
        self.verticalLayout_mon_03.setObjectName("verticalLayout_mon_03")
        self.gridLayout_5.addLayout(self.verticalLayout_mon_03, 0, 1, 1, 5)
        self.pushButton_plot_mon_03 = QtWidgets.QPushButton(self.groupBox_4)
        self.pushButton_plot_mon_03.setObjectName("pushButton_plot_mon_03")
        self.gridLayout_5.addWidget(self.pushButton_plot_mon_03, 2, 5, 1, 1)
        self.pushButton_plot_mon_03_clear = QtWidgets.QPushButton(self.groupBox_4)
        self.pushButton_plot_mon_03_clear.setObjectName("pushButton_plot_mon_03_clear")
        self.gridLayout_5.addWidget(self.pushButton_plot_mon_03_clear, 2, 4, 1, 1)
        self.verticalLayout_9.addLayout(self.gridLayout_5)
        self.gridLayout.addWidget(self.groupBox_4, 2, 0, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout)
        self.tabWidget.addTab(self.tab_plots_monitoring, "")
        self.tab_image_camera = QtWidgets.QWidget()
        self.tab_image_camera.setObjectName("tab_image_camera")
        self.verticalLayout_17 = QtWidgets.QVBoxLayout(self.tab_image_camera)
        self.verticalLayout_17.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout_17.setSpacing(6)
        self.verticalLayout_17.setObjectName("verticalLayout_17")
        self.gridLayout_16 = QtWidgets.QGridLayout()
        self.gridLayout_16.setContentsMargins(11, 11, 11, 11)
        self.gridLayout_16.setSpacing(6)
        self.gridLayout_16.setObjectName("gridLayout_16")
        self.groupBox_9 = QtWidgets.QGroupBox(self.tab_image_camera)
        self.groupBox_9.setObjectName("groupBox_9")
        self.verticalLayout_18 = QtWidgets.QVBoxLayout(self.groupBox_9)
        self.verticalLayout_18.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout_18.setSpacing(6)
        self.verticalLayout_18.setObjectName("verticalLayout_18")
        self.gridLayout_17 = QtWidgets.QGridLayout()
        self.gridLayout_17.setContentsMargins(11, 11, 11, 11)
        self.gridLayout_17.setSpacing(6)
        self.gridLayout_17.setObjectName("gridLayout_17")
        spacerItem44 = QtWidgets.QSpacerItem(40, 1, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_17.addItem(spacerItem44, 0, 1, 1, 1)
        self.pushButton_image_load_data = QtWidgets.QPushButton(self.groupBox_9)
        self.pushButton_image_load_data.setObjectName("pushButton_image_load_data")
        self.gridLayout_17.addWidget(self.pushButton_image_load_data, 1, 3, 1, 1)
        spacerItem45 = QtWidgets.QSpacerItem(40, 1, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_17.addItem(spacerItem45, 0, 3, 1, 1)
        spacerItem46 = QtWidgets.QSpacerItem(40, 1, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_17.addItem(spacerItem46, 0, 2, 1, 1)
        spacerItem47 = QtWidgets.QSpacerItem(40, 1, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_17.addItem(spacerItem47, 0, 0, 1, 1)
        self.pushButton_image_browse_data = QtWidgets.QPushButton(self.groupBox_9)
        self.pushButton_image_browse_data.setObjectName("pushButton_image_browse_data")
        self.gridLayout_17.addWidget(self.pushButton_image_browse_data, 1, 0, 1, 1)
        self.lineEdit_image_load_data = QtWidgets.QLineEdit(self.groupBox_9)
        self.lineEdit_image_load_data.setObjectName("lineEdit_image_load_data")
        self.gridLayout_17.addWidget(self.lineEdit_image_load_data, 1, 1, 1, 2)
        self.verticalLayout_18.addLayout(self.gridLayout_17)
        self.gridLayout_16.addWidget(self.groupBox_9, 1, 1, 1, 2)
        spacerItem48 = QtWidgets.QSpacerItem(1, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_16.addItem(spacerItem48, 3, 0, 1, 1)
        spacerItem49 = QtWidgets.QSpacerItem(40, 1, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_16.addItem(spacerItem49, 0, 2, 1, 1)
        spacerItem50 = QtWidgets.QSpacerItem(40, 1, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_16.addItem(spacerItem50, 0, 1, 1, 1)
        self.groupBox_10 = QtWidgets.QGroupBox(self.tab_image_camera)
        self.groupBox_10.setObjectName("groupBox_10")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.groupBox_10)
        self.verticalLayout_4.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout_4.setSpacing(6)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.gridLayout_8 = QtWidgets.QGridLayout()
        self.gridLayout_8.setContentsMargins(11, 11, 11, 11)
        self.gridLayout_8.setSpacing(6)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.label_9 = QtWidgets.QLabel(self.groupBox_10)
        self.label_9.setObjectName("label_9")
        self.gridLayout_8.addWidget(self.label_9, 9, 1, 1, 1)
        spacerItem51 = QtWidgets.QSpacerItem(40, 1, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_8.addItem(spacerItem51, 0, 3, 1, 1)
        spacerItem52 = QtWidgets.QSpacerItem(1, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_8.addItem(spacerItem52, 12, 5, 1, 1)
        spacerItem53 = QtWidgets.QSpacerItem(1, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_8.addItem(spacerItem53, 13, 5, 1, 1)
        spacerItem54 = QtWidgets.QSpacerItem(1, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_8.addItem(spacerItem54, 11, 5, 1, 1)
        spacerItem55 = QtWidgets.QSpacerItem(1, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_8.addItem(spacerItem55, 8, 5, 1, 1)
        spacerItem56 = QtWidgets.QSpacerItem(40, 1, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_8.addItem(spacerItem56, 0, 2, 1, 1)
        spacerItem57 = QtWidgets.QSpacerItem(40, 1, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_8.addItem(spacerItem57, 0, 0, 1, 1)
        self.pushButton_image_filter = QtWidgets.QPushButton(self.groupBox_10)
        self.pushButton_image_filter.setObjectName("pushButton_image_filter")
        self.gridLayout_8.addWidget(self.pushButton_image_filter, 3, 4, 1, 1)
        spacerItem58 = QtWidgets.QSpacerItem(1, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_8.addItem(spacerItem58, 5, 5, 1, 1)
        self.pushButton_image_rotate = QtWidgets.QPushButton(self.groupBox_10)
        self.pushButton_image_rotate.setObjectName("pushButton_image_rotate")
        self.gridLayout_8.addWidget(self.pushButton_image_rotate, 1, 4, 1, 1)
        spacerItem59 = QtWidgets.QSpacerItem(1, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_8.addItem(spacerItem59, 3, 5, 1, 1)
        self.label = QtWidgets.QLabel(self.groupBox_10)
        self.label.setObjectName("label")
        self.gridLayout_8.addWidget(self.label, 3, 0, 1, 1)
        spacerItem60 = QtWidgets.QSpacerItem(1, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_8.addItem(spacerItem60, 6, 5, 1, 1)
        spacerItem61 = QtWidgets.QSpacerItem(40, 1, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_8.addItem(spacerItem61, 0, 4, 1, 1)
        spacerItem62 = QtWidgets.QSpacerItem(1, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_8.addItem(spacerItem62, 9, 5, 1, 1)
        spacerItem63 = QtWidgets.QSpacerItem(1, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_8.addItem(spacerItem63, 1, 5, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.groupBox_10)
        self.label_2.setObjectName("label_2")
        self.gridLayout_8.addWidget(self.label_2, 1, 0, 1, 1)
        spacerItem64 = QtWidgets.QSpacerItem(40, 1, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_8.addItem(spacerItem64, 0, 1, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.groupBox_10)
        self.label_6.setObjectName("label_6")
        self.gridLayout_8.addWidget(self.label_6, 5, 3, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.groupBox_10)
        self.label_3.setObjectName("label_3")
        self.gridLayout_8.addWidget(self.label_3, 5, 0, 1, 1)
        self.line = QtWidgets.QFrame(self.groupBox_10)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridLayout_8.addWidget(self.line, 2, 0, 1, 5)
        self.label_4 = QtWidgets.QLabel(self.groupBox_10)
        self.label_4.setObjectName("label_4")
        self.gridLayout_8.addWidget(self.label_4, 6, 1, 1, 1)
        self.line_2 = QtWidgets.QFrame(self.groupBox_10)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.gridLayout_8.addWidget(self.line_2, 4, 0, 1, 5)
        self.pushButton_image_ellipse = QtWidgets.QPushButton(self.groupBox_10)
        self.pushButton_image_ellipse.setObjectName("pushButton_image_ellipse")
        self.gridLayout_8.addWidget(self.pushButton_image_ellipse, 8, 4, 1, 1)
        self.doubleSpinBox_image_edges_sigma = QtWidgets.QDoubleSpinBox(self.groupBox_10)
        self.doubleSpinBox_image_edges_sigma.setAlignment(QtCore.Qt.AlignCenter)
        self.doubleSpinBox_image_edges_sigma.setProperty("value", 6.0)
        self.doubleSpinBox_image_edges_sigma.setObjectName("doubleSpinBox_image_edges_sigma")
        self.gridLayout_8.addWidget(self.doubleSpinBox_image_edges_sigma, 6, 2, 1, 1)
        self.pushButton_image_edges = QtWidgets.QPushButton(self.groupBox_10)
        self.pushButton_image_edges.setObjectName("pushButton_image_edges")
        self.gridLayout_8.addWidget(self.pushButton_image_edges, 6, 4, 1, 1)
        self.doubleSpinBox_image_edges_low_threshold = QtWidgets.QDoubleSpinBox(self.groupBox_10)
        self.doubleSpinBox_image_edges_low_threshold.setAlignment(QtCore.Qt.AlignCenter)
        self.doubleSpinBox_image_edges_low_threshold.setProperty("value", 0.1)
        self.doubleSpinBox_image_edges_low_threshold.setObjectName("doubleSpinBox_image_edges_low_threshold")
        self.gridLayout_8.addWidget(self.doubleSpinBox_image_edges_low_threshold, 5, 2, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.groupBox_10)
        self.label_5.setObjectName("label_5")
        self.gridLayout_8.addWidget(self.label_5, 5, 1, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.groupBox_10)
        self.label_8.setObjectName("label_8")
        self.gridLayout_8.addWidget(self.label_8, 8, 1, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.groupBox_10)
        self.label_7.setObjectName("label_7")
        self.gridLayout_8.addWidget(self.label_7, 8, 0, 1, 1)
        spacerItem65 = QtWidgets.QSpacerItem(1, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_8.addItem(spacerItem65, 15, 5, 1, 1)
        self.doubleSpinBox_image_edges_high_threshold = QtWidgets.QDoubleSpinBox(self.groupBox_10)
        self.doubleSpinBox_image_edges_high_threshold.setAlignment(QtCore.Qt.AlignCenter)
        self.doubleSpinBox_image_edges_high_threshold.setProperty("value", 0.5)
        self.doubleSpinBox_image_edges_high_threshold.setObjectName("doubleSpinBox_image_edges_high_threshold")
        self.gridLayout_8.addWidget(self.doubleSpinBox_image_edges_high_threshold, 5, 4, 1, 1)
        self.doubleSpinBox_image_magnification = QtWidgets.QDoubleSpinBox(self.groupBox_10)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.doubleSpinBox_image_magnification.sizePolicy().hasHeightForWidth())
        self.doubleSpinBox_image_magnification.setSizePolicy(sizePolicy)
        self.doubleSpinBox_image_magnification.setAlignment(QtCore.Qt.AlignCenter)
        self.doubleSpinBox_image_magnification.setDecimals(8)
        self.doubleSpinBox_image_magnification.setMaximum(1.0)
        self.doubleSpinBox_image_magnification.setSingleStep(1e-06)
        self.doubleSpinBox_image_magnification.setProperty("value", 2e-06)
        self.doubleSpinBox_image_magnification.setObjectName("doubleSpinBox_image_magnification")
        self.gridLayout_8.addWidget(self.doubleSpinBox_image_magnification, 8, 2, 1, 1)
        self.line_3 = QtWidgets.QFrame(self.groupBox_10)
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.gridLayout_8.addWidget(self.line_3, 7, 0, 1, 5)
        self.doubleSpinBox_image_filter_threshold = QtWidgets.QDoubleSpinBox(self.groupBox_10)
        self.doubleSpinBox_image_filter_threshold.setAlignment(QtCore.Qt.AlignCenter)
        self.doubleSpinBox_image_filter_threshold.setDecimals(1)
        self.doubleSpinBox_image_filter_threshold.setProperty("value", 1.5)
        self.doubleSpinBox_image_filter_threshold.setObjectName("doubleSpinBox_image_filter_threshold")
        self.gridLayout_8.addWidget(self.doubleSpinBox_image_filter_threshold, 3, 2, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.groupBox_10)
        self.label_12.setObjectName("label_12")
        self.gridLayout_8.addWidget(self.label_12, 11, 1, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.groupBox_10)
        self.label_10.setObjectName("label_10")
        self.gridLayout_8.addWidget(self.label_10, 11, 0, 1, 1)
        self.label_image_volume = QtWidgets.QLabel(self.groupBox_10)
        self.label_image_volume.setAlignment(QtCore.Qt.AlignCenter)
        self.label_image_volume.setObjectName("label_image_volume")
        self.gridLayout_8.addWidget(self.label_image_volume, 9, 2, 1, 1)
        self.line_4 = QtWidgets.QFrame(self.groupBox_10)
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.gridLayout_8.addWidget(self.line_4, 10, 0, 1, 5)
        self.label_14 = QtWidgets.QLabel(self.groupBox_10)
        self.label_14.setObjectName("label_14")
        self.gridLayout_8.addWidget(self.label_14, 11, 3, 1, 1)
        self.spinBox_image_ion_mass = QtWidgets.QSpinBox(self.groupBox_10)
        self.spinBox_image_ion_mass.setAlignment(QtCore.Qt.AlignCenter)
        self.spinBox_image_ion_mass.setMaximum(200)
        self.spinBox_image_ion_mass.setProperty("value", 9)
        self.spinBox_image_ion_mass.setObjectName("spinBox_image_ion_mass")
        self.gridLayout_8.addWidget(self.spinBox_image_ion_mass, 11, 2, 1, 1)
        self.doubleSpinBox_image_rf_amplitude = QtWidgets.QDoubleSpinBox(self.groupBox_10)
        self.doubleSpinBox_image_rf_amplitude.setAlignment(QtCore.Qt.AlignCenter)
        self.doubleSpinBox_image_rf_amplitude.setMaximum(1000.0)
        self.doubleSpinBox_image_rf_amplitude.setProperty("value", 235.0)
        self.doubleSpinBox_image_rf_amplitude.setObjectName("doubleSpinBox_image_rf_amplitude")
        self.gridLayout_8.addWidget(self.doubleSpinBox_image_rf_amplitude, 12, 4, 1, 1)
        self.label_13 = QtWidgets.QLabel(self.groupBox_10)
        self.label_13.setObjectName("label_13")
        self.gridLayout_8.addWidget(self.label_13, 12, 3, 1, 1)
        self.doubleSpinBox_image_frequency = QtWidgets.QDoubleSpinBox(self.groupBox_10)
        self.doubleSpinBox_image_frequency.setAlignment(QtCore.Qt.AlignCenter)
        self.doubleSpinBox_image_frequency.setDecimals(3)
        self.doubleSpinBox_image_frequency.setMaximum(50.0)
        self.doubleSpinBox_image_frequency.setProperty("value", 13.335)
        self.doubleSpinBox_image_frequency.setObjectName("doubleSpinBox_image_frequency")
        self.gridLayout_8.addWidget(self.doubleSpinBox_image_frequency, 12, 2, 1, 1)
        self.label_16 = QtWidgets.QLabel(self.groupBox_10)
        self.label_16.setObjectName("label_16")
        self.gridLayout_8.addWidget(self.label_16, 13, 1, 1, 1)
        self.doubleSpinBox_image_r_0 = QtWidgets.QDoubleSpinBox(self.groupBox_10)
        self.doubleSpinBox_image_r_0.setAlignment(QtCore.Qt.AlignCenter)
        self.doubleSpinBox_image_r_0.setDecimals(8)
        self.doubleSpinBox_image_r_0.setSingleStep(0.0001)
        self.doubleSpinBox_image_r_0.setProperty("value", 0.003481)
        self.doubleSpinBox_image_r_0.setObjectName("doubleSpinBox_image_r_0")
        self.gridLayout_8.addWidget(self.doubleSpinBox_image_r_0, 11, 4, 1, 1)
        self.label_image_ion_number = QtWidgets.QLabel(self.groupBox_10)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_image_ion_number.setFont(font)
        self.label_image_ion_number.setAlignment(QtCore.Qt.AlignCenter)
        self.label_image_ion_number.setObjectName("label_image_ion_number")
        self.gridLayout_8.addWidget(self.label_image_ion_number, 13, 2, 1, 1)
        self.label_15 = QtWidgets.QLabel(self.groupBox_10)
        self.label_15.setObjectName("label_15")
        self.gridLayout_8.addWidget(self.label_15, 12, 1, 1, 1)
        self.pushButton_image_get_ion_number = QtWidgets.QPushButton(self.groupBox_10)
        self.pushButton_image_get_ion_number.setObjectName("pushButton_image_get_ion_number")
        self.gridLayout_8.addWidget(self.pushButton_image_get_ion_number, 13, 4, 1, 1)
        self.pushButton_image_inner_structure = QtWidgets.QPushButton(self.groupBox_10)
        self.pushButton_image_inner_structure.setObjectName("pushButton_image_inner_structure")
        self.gridLayout_8.addWidget(self.pushButton_image_inner_structure, 15, 4, 1, 1)
        self.line_5 = QtWidgets.QFrame(self.groupBox_10)
        self.line_5.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.gridLayout_8.addWidget(self.line_5, 14, 0, 1, 5)
        spacerItem66 = QtWidgets.QSpacerItem(1, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_8.addItem(spacerItem66, 16, 5, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.groupBox_10)
        self.label_11.setObjectName("label_11")
        self.gridLayout_8.addWidget(self.label_11, 15, 0, 1, 1)
        self.label_image_fraction = QtWidgets.QLabel(self.groupBox_10)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_image_fraction.setFont(font)
        self.label_image_fraction.setAlignment(QtCore.Qt.AlignCenter)
        self.label_image_fraction.setObjectName("label_image_fraction")
        self.gridLayout_8.addWidget(self.label_image_fraction, 16, 2, 1, 1)
        self.label_17 = QtWidgets.QLabel(self.groupBox_10)
        self.label_17.setObjectName("label_17")
        self.gridLayout_8.addWidget(self.label_17, 16, 1, 1, 1)
        spacerItem67 = QtWidgets.QSpacerItem(1, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_8.addItem(spacerItem67, 17, 5, 1, 1)
        self.label_21 = QtWidgets.QLabel(self.groupBox_10)
        self.label_21.setObjectName("label_21")
        self.gridLayout_8.addWidget(self.label_21, 17, 3, 1, 1)
        self.label_image_ion_number_corrected = QtWidgets.QLabel(self.groupBox_10)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_image_ion_number_corrected.setFont(font)
        self.label_image_ion_number_corrected.setAlignment(QtCore.Qt.AlignCenter)
        self.label_image_ion_number_corrected.setObjectName("label_image_ion_number_corrected")
        self.gridLayout_8.addWidget(self.label_image_ion_number_corrected, 17, 2, 1, 1)
        self.label_19 = QtWidgets.QLabel(self.groupBox_10)
        self.label_19.setObjectName("label_19")
        self.gridLayout_8.addWidget(self.label_19, 17, 1, 1, 1)
        self.label_image_ion_number_dark = QtWidgets.QLabel(self.groupBox_10)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_image_ion_number_dark.setFont(font)
        self.label_image_ion_number_dark.setAlignment(QtCore.Qt.AlignCenter)
        self.label_image_ion_number_dark.setObjectName("label_image_ion_number_dark")
        self.gridLayout_8.addWidget(self.label_image_ion_number_dark, 17, 4, 1, 1)
        self.verticalLayout_4.addLayout(self.gridLayout_8)
        self.gridLayout_16.addWidget(self.groupBox_10, 2, 2, 2, 1)
        spacerItem68 = QtWidgets.QSpacerItem(1, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_16.addItem(spacerItem68, 2, 0, 1, 1)
        self.verticalLayout_image = QtWidgets.QVBoxLayout()
        self.verticalLayout_image.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout_image.setSpacing(6)
        self.verticalLayout_image.setObjectName("verticalLayout_image")
        self.gridLayout_16.addLayout(self.verticalLayout_image, 2, 1, 2, 1)
        self.verticalLayout_17.addLayout(self.gridLayout_16)
        self.tabWidget.addTab(self.tab_image_camera, "")
        self.tab_image_series = QtWidgets.QWidget()
        self.tab_image_series.setObjectName("tab_image_series")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.tab_image_series)
        self.verticalLayout_5.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout_5.setSpacing(6)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.gridLayout_9 = QtWidgets.QGridLayout()
        self.gridLayout_9.setContentsMargins(11, 11, 11, 11)
        self.gridLayout_9.setSpacing(6)
        self.gridLayout_9.setObjectName("gridLayout_9")
        spacerItem69 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_9.addItem(spacerItem69, 0, 2, 1, 1)
        self.pushButton_image_save_series = QtWidgets.QPushButton(self.tab_image_series)
        self.pushButton_image_save_series.setObjectName("pushButton_image_save_series")
        self.gridLayout_9.addWidget(self.pushButton_image_save_series, 2, 2, 1, 1)
        spacerItem70 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_9.addItem(spacerItem70, 0, 1, 1, 1)
        self.pushButton_image_browse_multiple_data = QtWidgets.QPushButton(self.tab_image_series)
        self.pushButton_image_browse_multiple_data.setObjectName("pushButton_image_browse_multiple_data")
        self.gridLayout_9.addWidget(self.pushButton_image_browse_multiple_data, 1, 2, 1, 1)
        spacerItem71 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_9.addItem(spacerItem71, 1, 0, 1, 1)
        spacerItem72 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_9.addItem(spacerItem72, 2, 0, 1, 1)
        self.verticalLayout_series_results = QtWidgets.QVBoxLayout()
        self.verticalLayout_series_results.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout_series_results.setSpacing(6)
        self.verticalLayout_series_results.setObjectName("verticalLayout_series_results")
        self.gridLayout_9.addLayout(self.verticalLayout_series_results, 1, 1, 2, 1)
        self.verticalLayout_5.addLayout(self.gridLayout_9)
        self.tabWidget.addTab(self.tab_image_series, "")
        self.verticalLayout.addWidget(self.tabWidget)
        XAn.setCentralWidget(self.centralWidget)
        self.statusBar = QtWidgets.QStatusBar(XAn)
        self.statusBar.setObjectName("statusBar")
        XAn.setStatusBar(self.statusBar)

        self.retranslateUi(XAn)
        self.tabWidget.setCurrentIndex(1)
        self.comboBox_plot_5_y.setCurrentIndex(22)
        self.comboBox_plot_2_y.setCurrentIndex(21)
        self.comboBox_plot_6_y.setCurrentIndex(16)
        self.comboBox_plot_4_y.setCurrentIndex(11)
        self.comboBox_plot_1_y.setCurrentIndex(20)
        self.comboBox_plot_3_y.setCurrentIndex(9)
        QtCore.QMetaObject.connectSlotsByName(XAn)

    def retranslateUi(self, XAn):
        _translate = QtCore.QCoreApplication.translate
        XAn.setWindowTitle(_translate("XAn", "XAn"))
        self.groupBox_6.setTitle(_translate("XAn", "plot 5"))
        self.comboBox_plot_5_x.setItemText(0, _translate("XAn", "t"))
        self.comboBox_plot_5_x.setItemText(1, _translate("XAn", "dc_el_1"))
        self.comboBox_plot_5_x.setItemText(2, _translate("XAn", "dc_el_2"))
        self.comboBox_plot_5_x.setItemText(3, _translate("XAn", "dc_el_3"))
        self.comboBox_plot_5_x.setItemText(4, _translate("XAn", "dc_el_4"))
        self.comboBox_plot_5_x.setItemText(5, _translate("XAn", "dc_el_5"))
        self.comboBox_plot_5_x.setItemText(6, _translate("XAn", "dc_el_6"))
        self.comboBox_plot_5_x.setItemText(7, _translate("XAn", "dc_el_7"))
        self.comboBox_plot_5_x.setItemText(8, _translate("XAn", "dc_el_8"))
        self.comboBox_plot_5_x.setItemText(9, _translate("XAn", "rf_ampl"))
        self.comboBox_plot_5_x.setItemText(10, _translate("XAn", "rf_freq"))
        self.comboBox_plot_5_x.setItemText(11, _translate("XAn", "i_oven"))
        self.comboBox_plot_5_x.setItemText(12, _translate("XAn", "i_egun"))
        self.comboBox_plot_5_x.setItemText(13, _translate("XAn", "u_egun_filament"))
        self.comboBox_plot_5_x.setItemText(14, _translate("XAn", "u_egun_wehnelt"))
        self.comboBox_plot_5_x.setItemText(15, _translate("XAn", "freq_313"))
        self.comboBox_plot_5_x.setItemText(16, _translate("XAn", "pressure"))
        self.comboBox_plot_5_x.setItemText(17, _translate("XAn", "cam_temp"))
        self.comboBox_plot_5_x.setItemText(18, _translate("XAn", "cam_exp"))
        self.comboBox_plot_5_x.setItemText(19, _translate("XAn", "cam_gain"))
        self.comboBox_plot_5_x.setItemText(20, _translate("XAn", "U_endc"))
        self.comboBox_plot_5_x.setItemText(21, _translate("XAn", "U_0"))
        self.comboBox_plot_5_x.setItemText(22, _translate("XAn", "freq_313_relative"))
        self.comboBox_plot_5_y.setItemText(0, _translate("XAn", "t"))
        self.comboBox_plot_5_y.setItemText(1, _translate("XAn", "dc_el_1"))
        self.comboBox_plot_5_y.setItemText(2, _translate("XAn", "dc_el_2"))
        self.comboBox_plot_5_y.setItemText(3, _translate("XAn", "dc_el_3"))
        self.comboBox_plot_5_y.setItemText(4, _translate("XAn", "dc_el_4"))
        self.comboBox_plot_5_y.setItemText(5, _translate("XAn", "dc_el_5"))
        self.comboBox_plot_5_y.setItemText(6, _translate("XAn", "dc_el_6"))
        self.comboBox_plot_5_y.setItemText(7, _translate("XAn", "dc_el_7"))
        self.comboBox_plot_5_y.setItemText(8, _translate("XAn", "dc_el_8"))
        self.comboBox_plot_5_y.setItemText(9, _translate("XAn", "rf_ampl"))
        self.comboBox_plot_5_y.setItemText(10, _translate("XAn", "rf_freq"))
        self.comboBox_plot_5_y.setItemText(11, _translate("XAn", "i_oven"))
        self.comboBox_plot_5_y.setItemText(12, _translate("XAn", "i_egun"))
        self.comboBox_plot_5_y.setItemText(13, _translate("XAn", "u_egun_filament"))
        self.comboBox_plot_5_y.setItemText(14, _translate("XAn", "u_egun_wehnelt"))
        self.comboBox_plot_5_y.setItemText(15, _translate("XAn", "freq_313"))
        self.comboBox_plot_5_y.setItemText(16, _translate("XAn", "pressure"))
        self.comboBox_plot_5_y.setItemText(17, _translate("XAn", "cam_temp"))
        self.comboBox_plot_5_y.setItemText(18, _translate("XAn", "cam_exp"))
        self.comboBox_plot_5_y.setItemText(19, _translate("XAn", "cam_gain"))
        self.comboBox_plot_5_y.setItemText(20, _translate("XAn", "U_endc"))
        self.comboBox_plot_5_y.setItemText(21, _translate("XAn", "U_0"))
        self.comboBox_plot_5_y.setItemText(22, _translate("XAn", "freq_313_relative"))
        self.pushButton_plot_mon_05.setText(_translate("XAn", "plot"))
        self.pushButton_plot_mon_05_clear.setText(_translate("XAn", "clear"))
        self.groupBox_3.setTitle(_translate("XAn", "plot 2"))
        self.comboBox_plot_2_x.setItemText(0, _translate("XAn", "t"))
        self.comboBox_plot_2_x.setItemText(1, _translate("XAn", "dc_el_1"))
        self.comboBox_plot_2_x.setItemText(2, _translate("XAn", "dc_el_2"))
        self.comboBox_plot_2_x.setItemText(3, _translate("XAn", "dc_el_3"))
        self.comboBox_plot_2_x.setItemText(4, _translate("XAn", "dc_el_4"))
        self.comboBox_plot_2_x.setItemText(5, _translate("XAn", "dc_el_5"))
        self.comboBox_plot_2_x.setItemText(6, _translate("XAn", "dc_el_6"))
        self.comboBox_plot_2_x.setItemText(7, _translate("XAn", "dc_el_7"))
        self.comboBox_plot_2_x.setItemText(8, _translate("XAn", "dc_el_8"))
        self.comboBox_plot_2_x.setItemText(9, _translate("XAn", "rf_ampl"))
        self.comboBox_plot_2_x.setItemText(10, _translate("XAn", "rf_freq"))
        self.comboBox_plot_2_x.setItemText(11, _translate("XAn", "i_oven"))
        self.comboBox_plot_2_x.setItemText(12, _translate("XAn", "i_egun"))
        self.comboBox_plot_2_x.setItemText(13, _translate("XAn", "u_egun_filament"))
        self.comboBox_plot_2_x.setItemText(14, _translate("XAn", "u_egun_wehnelt"))
        self.comboBox_plot_2_x.setItemText(15, _translate("XAn", "freq_313"))
        self.comboBox_plot_2_x.setItemText(16, _translate("XAn", "pressure"))
        self.comboBox_plot_2_x.setItemText(17, _translate("XAn", "cam_temp"))
        self.comboBox_plot_2_x.setItemText(18, _translate("XAn", "cam_exp"))
        self.comboBox_plot_2_x.setItemText(19, _translate("XAn", "cam_gain"))
        self.comboBox_plot_2_x.setItemText(20, _translate("XAn", "U_endc"))
        self.comboBox_plot_2_x.setItemText(21, _translate("XAn", "U_0"))
        self.comboBox_plot_2_x.setItemText(22, _translate("XAn", "freq_313_relative"))
        self.comboBox_plot_2_y.setItemText(0, _translate("XAn", "t"))
        self.comboBox_plot_2_y.setItemText(1, _translate("XAn", "dc_el_1"))
        self.comboBox_plot_2_y.setItemText(2, _translate("XAn", "dc_el_2"))
        self.comboBox_plot_2_y.setItemText(3, _translate("XAn", "dc_el_3"))
        self.comboBox_plot_2_y.setItemText(4, _translate("XAn", "dc_el_4"))
        self.comboBox_plot_2_y.setItemText(5, _translate("XAn", "dc_el_5"))
        self.comboBox_plot_2_y.setItemText(6, _translate("XAn", "dc_el_6"))
        self.comboBox_plot_2_y.setItemText(7, _translate("XAn", "dc_el_7"))
        self.comboBox_plot_2_y.setItemText(8, _translate("XAn", "dc_el_8"))
        self.comboBox_plot_2_y.setItemText(9, _translate("XAn", "rf_ampl"))
        self.comboBox_plot_2_y.setItemText(10, _translate("XAn", "rf_freq"))
        self.comboBox_plot_2_y.setItemText(11, _translate("XAn", "i_oven"))
        self.comboBox_plot_2_y.setItemText(12, _translate("XAn", "i_egun"))
        self.comboBox_plot_2_y.setItemText(13, _translate("XAn", "u_egun_filament"))
        self.comboBox_plot_2_y.setItemText(14, _translate("XAn", "u_egun_wehnelt"))
        self.comboBox_plot_2_y.setItemText(15, _translate("XAn", "freq_313"))
        self.comboBox_plot_2_y.setItemText(16, _translate("XAn", "pressure"))
        self.comboBox_plot_2_y.setItemText(17, _translate("XAn", "cam_temp"))
        self.comboBox_plot_2_y.setItemText(18, _translate("XAn", "cam_exp"))
        self.comboBox_plot_2_y.setItemText(19, _translate("XAn", "cam_gain"))
        self.comboBox_plot_2_y.setItemText(20, _translate("XAn", "U_endc"))
        self.comboBox_plot_2_y.setItemText(21, _translate("XAn", "U_0"))
        self.comboBox_plot_2_y.setItemText(22, _translate("XAn", "freq_313_relative"))
        self.pushButton_plot_mon_02.setText(_translate("XAn", "plot"))
        self.pushButton_plot_mon_02_clear.setText(_translate("XAn", "clear"))
        self.groupBox_7.setTitle(_translate("XAn", "plot 6"))
        self.comboBox_plot_6_y.setItemText(0, _translate("XAn", "t"))
        self.comboBox_plot_6_y.setItemText(1, _translate("XAn", "dc_el_1"))
        self.comboBox_plot_6_y.setItemText(2, _translate("XAn", "dc_el_2"))
        self.comboBox_plot_6_y.setItemText(3, _translate("XAn", "dc_el_3"))
        self.comboBox_plot_6_y.setItemText(4, _translate("XAn", "dc_el_4"))
        self.comboBox_plot_6_y.setItemText(5, _translate("XAn", "dc_el_5"))
        self.comboBox_plot_6_y.setItemText(6, _translate("XAn", "dc_el_6"))
        self.comboBox_plot_6_y.setItemText(7, _translate("XAn", "dc_el_7"))
        self.comboBox_plot_6_y.setItemText(8, _translate("XAn", "dc_el_8"))
        self.comboBox_plot_6_y.setItemText(9, _translate("XAn", "rf_ampl"))
        self.comboBox_plot_6_y.setItemText(10, _translate("XAn", "rf_freq"))
        self.comboBox_plot_6_y.setItemText(11, _translate("XAn", "i_oven"))
        self.comboBox_plot_6_y.setItemText(12, _translate("XAn", "i_egun"))
        self.comboBox_plot_6_y.setItemText(13, _translate("XAn", "u_egun_filament"))
        self.comboBox_plot_6_y.setItemText(14, _translate("XAn", "u_egun_wehnelt"))
        self.comboBox_plot_6_y.setItemText(15, _translate("XAn", "freq_313"))
        self.comboBox_plot_6_y.setItemText(16, _translate("XAn", "pressure"))
        self.comboBox_plot_6_y.setItemText(17, _translate("XAn", "cam_temp"))
        self.comboBox_plot_6_y.setItemText(18, _translate("XAn", "cam_exp"))
        self.comboBox_plot_6_y.setItemText(19, _translate("XAn", "cam_gain"))
        self.comboBox_plot_6_y.setItemText(20, _translate("XAn", "U_endc"))
        self.comboBox_plot_6_y.setItemText(21, _translate("XAn", "U_0"))
        self.comboBox_plot_6_y.setItemText(22, _translate("XAn", "freq_313_relative"))
        self.comboBox_plot_6_x.setItemText(0, _translate("XAn", "t"))
        self.comboBox_plot_6_x.setItemText(1, _translate("XAn", "dc_el_1"))
        self.comboBox_plot_6_x.setItemText(2, _translate("XAn", "dc_el_2"))
        self.comboBox_plot_6_x.setItemText(3, _translate("XAn", "dc_el_3"))
        self.comboBox_plot_6_x.setItemText(4, _translate("XAn", "dc_el_4"))
        self.comboBox_plot_6_x.setItemText(5, _translate("XAn", "dc_el_5"))
        self.comboBox_plot_6_x.setItemText(6, _translate("XAn", "dc_el_6"))
        self.comboBox_plot_6_x.setItemText(7, _translate("XAn", "dc_el_7"))
        self.comboBox_plot_6_x.setItemText(8, _translate("XAn", "dc_el_8"))
        self.comboBox_plot_6_x.setItemText(9, _translate("XAn", "rf_ampl"))
        self.comboBox_plot_6_x.setItemText(10, _translate("XAn", "rf_freq"))
        self.comboBox_plot_6_x.setItemText(11, _translate("XAn", "i_oven"))
        self.comboBox_plot_6_x.setItemText(12, _translate("XAn", "i_egun"))
        self.comboBox_plot_6_x.setItemText(13, _translate("XAn", "u_egun_filament"))
        self.comboBox_plot_6_x.setItemText(14, _translate("XAn", "u_egun_wehnelt"))
        self.comboBox_plot_6_x.setItemText(15, _translate("XAn", "freq_313"))
        self.comboBox_plot_6_x.setItemText(16, _translate("XAn", "pressure"))
        self.comboBox_plot_6_x.setItemText(17, _translate("XAn", "cam_temp"))
        self.comboBox_plot_6_x.setItemText(18, _translate("XAn", "cam_exp"))
        self.comboBox_plot_6_x.setItemText(19, _translate("XAn", "cam_gain"))
        self.comboBox_plot_6_x.setItemText(20, _translate("XAn", "U_endc"))
        self.comboBox_plot_6_x.setItemText(21, _translate("XAn", "U_0"))
        self.comboBox_plot_6_x.setItemText(22, _translate("XAn", "freq_313_relative"))
        self.pushButton_plot_mon_06.setText(_translate("XAn", "plot"))
        self.pushButton_plot_mon_06_clear.setText(_translate("XAn", "clear"))
        self.groupBox_5.setTitle(_translate("XAn", "plot 4"))
        self.comboBox_plot_4_x.setItemText(0, _translate("XAn", "t"))
        self.comboBox_plot_4_x.setItemText(1, _translate("XAn", "dc_el_1"))
        self.comboBox_plot_4_x.setItemText(2, _translate("XAn", "dc_el_2"))
        self.comboBox_plot_4_x.setItemText(3, _translate("XAn", "dc_el_3"))
        self.comboBox_plot_4_x.setItemText(4, _translate("XAn", "dc_el_4"))
        self.comboBox_plot_4_x.setItemText(5, _translate("XAn", "dc_el_5"))
        self.comboBox_plot_4_x.setItemText(6, _translate("XAn", "dc_el_6"))
        self.comboBox_plot_4_x.setItemText(7, _translate("XAn", "dc_el_7"))
        self.comboBox_plot_4_x.setItemText(8, _translate("XAn", "dc_el_8"))
        self.comboBox_plot_4_x.setItemText(9, _translate("XAn", "rf_ampl"))
        self.comboBox_plot_4_x.setItemText(10, _translate("XAn", "rf_freq"))
        self.comboBox_plot_4_x.setItemText(11, _translate("XAn", "i_oven"))
        self.comboBox_plot_4_x.setItemText(12, _translate("XAn", "i_egun"))
        self.comboBox_plot_4_x.setItemText(13, _translate("XAn", "u_egun_filament"))
        self.comboBox_plot_4_x.setItemText(14, _translate("XAn", "u_egun_wehnelt"))
        self.comboBox_plot_4_x.setItemText(15, _translate("XAn", "freq_313"))
        self.comboBox_plot_4_x.setItemText(16, _translate("XAn", "pressure"))
        self.comboBox_plot_4_x.setItemText(17, _translate("XAn", "cam_temp"))
        self.comboBox_plot_4_x.setItemText(18, _translate("XAn", "cam_exp"))
        self.comboBox_plot_4_x.setItemText(19, _translate("XAn", "cam_gain"))
        self.comboBox_plot_4_x.setItemText(20, _translate("XAn", "U_endc"))
        self.comboBox_plot_4_x.setItemText(21, _translate("XAn", "U_0"))
        self.comboBox_plot_4_x.setItemText(22, _translate("XAn", "freq_313_relative"))
        self.comboBox_plot_4_y.setItemText(0, _translate("XAn", "t"))
        self.comboBox_plot_4_y.setItemText(1, _translate("XAn", "dc_el_1"))
        self.comboBox_plot_4_y.setItemText(2, _translate("XAn", "dc_el_2"))
        self.comboBox_plot_4_y.setItemText(3, _translate("XAn", "dc_el_3"))
        self.comboBox_plot_4_y.setItemText(4, _translate("XAn", "dc_el_4"))
        self.comboBox_plot_4_y.setItemText(5, _translate("XAn", "dc_el_5"))
        self.comboBox_plot_4_y.setItemText(6, _translate("XAn", "dc_el_6"))
        self.comboBox_plot_4_y.setItemText(7, _translate("XAn", "dc_el_7"))
        self.comboBox_plot_4_y.setItemText(8, _translate("XAn", "dc_el_8"))
        self.comboBox_plot_4_y.setItemText(9, _translate("XAn", "rf_ampl"))
        self.comboBox_plot_4_y.setItemText(10, _translate("XAn", "rf_freq"))
        self.comboBox_plot_4_y.setItemText(11, _translate("XAn", "i_oven"))
        self.comboBox_plot_4_y.setItemText(12, _translate("XAn", "i_egun"))
        self.comboBox_plot_4_y.setItemText(13, _translate("XAn", "u_egun_filament"))
        self.comboBox_plot_4_y.setItemText(14, _translate("XAn", "u_egun_wehnelt"))
        self.comboBox_plot_4_y.setItemText(15, _translate("XAn", "freq_313"))
        self.comboBox_plot_4_y.setItemText(16, _translate("XAn", "pressure"))
        self.comboBox_plot_4_y.setItemText(17, _translate("XAn", "cam_temp"))
        self.comboBox_plot_4_y.setItemText(18, _translate("XAn", "cam_exp"))
        self.comboBox_plot_4_y.setItemText(19, _translate("XAn", "cam_gain"))
        self.comboBox_plot_4_y.setItemText(20, _translate("XAn", "U_endc"))
        self.comboBox_plot_4_y.setItemText(21, _translate("XAn", "U_0"))
        self.comboBox_plot_4_y.setItemText(22, _translate("XAn", "freq_313_relative"))
        self.pushButton_plot_mon_04.setText(_translate("XAn", "plot"))
        self.pushButton_plot_mon_04_clear.setText(_translate("XAn", "clear"))
        self.groupBox_8.setTitle(_translate("XAn", "global"))
        self.pushButton_plot_mon_all.setText(_translate("XAn", "plot all"))
        self.pushButton_plot_mon_clear_all.setText(_translate("XAn", "clear all"))
        self.groupBox.setTitle(_translate("XAn", "import"))
        self.pushButton_monitoring_browse_data.setText(_translate("XAn", "browse folder"))
        self.pushButton_monitoring_load_data.setText(_translate("XAn", "load"))
        self.groupBox_2.setTitle(_translate("XAn", "plot 1"))
        self.comboBox_plot_1_y.setItemText(0, _translate("XAn", "t"))
        self.comboBox_plot_1_y.setItemText(1, _translate("XAn", "dc_el_1"))
        self.comboBox_plot_1_y.setItemText(2, _translate("XAn", "dc_el_2"))
        self.comboBox_plot_1_y.setItemText(3, _translate("XAn", "dc_el_3"))
        self.comboBox_plot_1_y.setItemText(4, _translate("XAn", "dc_el_4"))
        self.comboBox_plot_1_y.setItemText(5, _translate("XAn", "dc_el_5"))
        self.comboBox_plot_1_y.setItemText(6, _translate("XAn", "dc_el_6"))
        self.comboBox_plot_1_y.setItemText(7, _translate("XAn", "dc_el_7"))
        self.comboBox_plot_1_y.setItemText(8, _translate("XAn", "dc_el_8"))
        self.comboBox_plot_1_y.setItemText(9, _translate("XAn", "rf_ampl"))
        self.comboBox_plot_1_y.setItemText(10, _translate("XAn", "rf_freq"))
        self.comboBox_plot_1_y.setItemText(11, _translate("XAn", "i_oven"))
        self.comboBox_plot_1_y.setItemText(12, _translate("XAn", "i_egun"))
        self.comboBox_plot_1_y.setItemText(13, _translate("XAn", "u_egun_filament"))
        self.comboBox_plot_1_y.setItemText(14, _translate("XAn", "u_egun_wehnelt"))
        self.comboBox_plot_1_y.setItemText(15, _translate("XAn", "freq_313"))
        self.comboBox_plot_1_y.setItemText(16, _translate("XAn", "pressure"))
        self.comboBox_plot_1_y.setItemText(17, _translate("XAn", "cam_temp"))
        self.comboBox_plot_1_y.setItemText(18, _translate("XAn", "cam_exp"))
        self.comboBox_plot_1_y.setItemText(19, _translate("XAn", "cam_gain"))
        self.comboBox_plot_1_y.setItemText(20, _translate("XAn", "U_endc"))
        self.comboBox_plot_1_y.setItemText(21, _translate("XAn", "U_0"))
        self.comboBox_plot_1_y.setItemText(22, _translate("XAn", "freq_313_relative"))
        self.comboBox_plot_1_x.setItemText(0, _translate("XAn", "t"))
        self.comboBox_plot_1_x.setItemText(1, _translate("XAn", "dc_el_1"))
        self.comboBox_plot_1_x.setItemText(2, _translate("XAn", "dc_el_2"))
        self.comboBox_plot_1_x.setItemText(3, _translate("XAn", "dc_el_3"))
        self.comboBox_plot_1_x.setItemText(4, _translate("XAn", "dc_el_4"))
        self.comboBox_plot_1_x.setItemText(5, _translate("XAn", "dc_el_5"))
        self.comboBox_plot_1_x.setItemText(6, _translate("XAn", "dc_el_6"))
        self.comboBox_plot_1_x.setItemText(7, _translate("XAn", "dc_el_7"))
        self.comboBox_plot_1_x.setItemText(8, _translate("XAn", "dc_el_8"))
        self.comboBox_plot_1_x.setItemText(9, _translate("XAn", "rf_ampl"))
        self.comboBox_plot_1_x.setItemText(10, _translate("XAn", "rf_freq"))
        self.comboBox_plot_1_x.setItemText(11, _translate("XAn", "i_oven"))
        self.comboBox_plot_1_x.setItemText(12, _translate("XAn", "i_egun"))
        self.comboBox_plot_1_x.setItemText(13, _translate("XAn", "u_egun_filament"))
        self.comboBox_plot_1_x.setItemText(14, _translate("XAn", "u_egun_wehnelt"))
        self.comboBox_plot_1_x.setItemText(15, _translate("XAn", "freq_313"))
        self.comboBox_plot_1_x.setItemText(16, _translate("XAn", "pressure"))
        self.comboBox_plot_1_x.setItemText(17, _translate("XAn", "cam_temp"))
        self.comboBox_plot_1_x.setItemText(18, _translate("XAn", "cam_exp"))
        self.comboBox_plot_1_x.setItemText(19, _translate("XAn", "cam_gain"))
        self.comboBox_plot_1_x.setItemText(20, _translate("XAn", "U_endc"))
        self.comboBox_plot_1_x.setItemText(21, _translate("XAn", "U_0"))
        self.comboBox_plot_1_x.setItemText(22, _translate("XAn", "freq_313_relative"))
        self.pushButton_plot_mon_01.setText(_translate("XAn", "plot"))
        self.pushButton_plot_mon_01_clear.setText(_translate("XAn", "clear"))
        self.groupBox_4.setTitle(_translate("XAn", "plot 3"))
        self.comboBox_plot_3_x.setItemText(0, _translate("XAn", "t"))
        self.comboBox_plot_3_x.setItemText(1, _translate("XAn", "dc_el_1"))
        self.comboBox_plot_3_x.setItemText(2, _translate("XAn", "dc_el_2"))
        self.comboBox_plot_3_x.setItemText(3, _translate("XAn", "dc_el_3"))
        self.comboBox_plot_3_x.setItemText(4, _translate("XAn", "dc_el_4"))
        self.comboBox_plot_3_x.setItemText(5, _translate("XAn", "dc_el_5"))
        self.comboBox_plot_3_x.setItemText(6, _translate("XAn", "dc_el_6"))
        self.comboBox_plot_3_x.setItemText(7, _translate("XAn", "dc_el_7"))
        self.comboBox_plot_3_x.setItemText(8, _translate("XAn", "dc_el_8"))
        self.comboBox_plot_3_x.setItemText(9, _translate("XAn", "rf_ampl"))
        self.comboBox_plot_3_x.setItemText(10, _translate("XAn", "rf_freq"))
        self.comboBox_plot_3_x.setItemText(11, _translate("XAn", "i_oven"))
        self.comboBox_plot_3_x.setItemText(12, _translate("XAn", "i_egun"))
        self.comboBox_plot_3_x.setItemText(13, _translate("XAn", "u_egun_filament"))
        self.comboBox_plot_3_x.setItemText(14, _translate("XAn", "u_egun_wehnelt"))
        self.comboBox_plot_3_x.setItemText(15, _translate("XAn", "freq_313"))
        self.comboBox_plot_3_x.setItemText(16, _translate("XAn", "pressure"))
        self.comboBox_plot_3_x.setItemText(17, _translate("XAn", "cam_temp"))
        self.comboBox_plot_3_x.setItemText(18, _translate("XAn", "cam_exp"))
        self.comboBox_plot_3_x.setItemText(19, _translate("XAn", "cam_gain"))
        self.comboBox_plot_3_x.setItemText(20, _translate("XAn", "U_endc"))
        self.comboBox_plot_3_x.setItemText(21, _translate("XAn", "U_0"))
        self.comboBox_plot_3_x.setItemText(22, _translate("XAn", "freq_313_relative"))
        self.comboBox_plot_3_y.setItemText(0, _translate("XAn", "t"))
        self.comboBox_plot_3_y.setItemText(1, _translate("XAn", "dc_el_1"))
        self.comboBox_plot_3_y.setItemText(2, _translate("XAn", "dc_el_2"))
        self.comboBox_plot_3_y.setItemText(3, _translate("XAn", "dc_el_3"))
        self.comboBox_plot_3_y.setItemText(4, _translate("XAn", "dc_el_4"))
        self.comboBox_plot_3_y.setItemText(5, _translate("XAn", "dc_el_5"))
        self.comboBox_plot_3_y.setItemText(6, _translate("XAn", "dc_el_6"))
        self.comboBox_plot_3_y.setItemText(7, _translate("XAn", "dc_el_7"))
        self.comboBox_plot_3_y.setItemText(8, _translate("XAn", "dc_el_8"))
        self.comboBox_plot_3_y.setItemText(9, _translate("XAn", "rf_ampl"))
        self.comboBox_plot_3_y.setItemText(10, _translate("XAn", "rf_freq"))
        self.comboBox_plot_3_y.setItemText(11, _translate("XAn", "i_oven"))
        self.comboBox_plot_3_y.setItemText(12, _translate("XAn", "i_egun"))
        self.comboBox_plot_3_y.setItemText(13, _translate("XAn", "u_egun_filament"))
        self.comboBox_plot_3_y.setItemText(14, _translate("XAn", "u_egun_wehnelt"))
        self.comboBox_plot_3_y.setItemText(15, _translate("XAn", "freq_313"))
        self.comboBox_plot_3_y.setItemText(16, _translate("XAn", "pressure"))
        self.comboBox_plot_3_y.setItemText(17, _translate("XAn", "cam_temp"))
        self.comboBox_plot_3_y.setItemText(18, _translate("XAn", "cam_exp"))
        self.comboBox_plot_3_y.setItemText(19, _translate("XAn", "cam_gain"))
        self.comboBox_plot_3_y.setItemText(20, _translate("XAn", "U_endc"))
        self.comboBox_plot_3_y.setItemText(21, _translate("XAn", "U_0"))
        self.comboBox_plot_3_y.setItemText(22, _translate("XAn", "freq_313_relative"))
        self.pushButton_plot_mon_03.setText(_translate("XAn", "plot"))
        self.pushButton_plot_mon_03_clear.setText(_translate("XAn", "clear"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_plots_monitoring), _translate("XAn", "PLOTS monitoring"))
        self.groupBox_9.setTitle(_translate("XAn", "import"))
        self.pushButton_image_load_data.setText(_translate("XAn", "load"))
        self.pushButton_image_browse_data.setText(_translate("XAn", "browse folder"))
        self.groupBox_10.setTitle(_translate("XAn", "MANIPULATION AND ANALYSIS"))
        self.label_9.setText(_translate("XAn", " volume [m^3]:"))
        self.pushButton_image_filter.setText(_translate("XAn", "map"))
        self.pushButton_image_rotate.setText(_translate("XAn", "swap"))
        self.label.setText(_translate("XAn", " map threshold:"))
        self.label_2.setText(_translate("XAn", " swap axes"))
        self.label_6.setText(_translate("XAn", " high_threshold"))
        self.label_3.setText(_translate("XAn", " get edges: "))
        self.label_4.setText(_translate("XAn", " sigma"))
        self.pushButton_image_ellipse.setText(_translate("XAn", "ellipse"))
        self.pushButton_image_edges.setText(_translate("XAn", "edges"))
        self.label_5.setText(_translate("XAn", " low_threshold"))
        self.label_8.setText(_translate("XAn", " magnification [m/pixel]:"))
        self.label_7.setText(_translate("XAn", " get ellipse"))
        self.label_12.setText(_translate("XAn", " mass [au]:"))
        self.label_10.setText(_translate("XAn", " get ion number"))
        self.label_image_volume.setText(_translate("XAn", "0"))
        self.label_14.setText(_translate("XAn", " r_0 [m]:"))
        self.label_13.setText(_translate("XAn", " U_rf [V]:"))
        self.label_16.setText(_translate("XAn", " number of ions:"))
        self.label_image_ion_number.setText(_translate("XAn", "0"))
        self.label_15.setText(_translate("XAn", " f_rf [MHz]:"))
        self.pushButton_image_get_ion_number.setText(_translate("XAn", "ion number"))
        self.pushButton_image_inner_structure.setText(_translate("XAn", "correct"))
        self.label_11.setText(_translate("XAn", " correct for dark ions: "))
        self.label_image_fraction.setText(_translate("XAn", "0.0"))
        self.label_17.setText(_translate("XAn", " missing fraction:"))
        self.label_21.setText(_translate("XAn", " number dark ions: "))
        self.label_image_ion_number_corrected.setText(_translate("XAn", "0"))
        self.label_19.setText(_translate("XAn", " number outer ions:"))
        self.label_image_ion_number_dark.setText(_translate("XAn", "0"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_image_camera), _translate("XAn", "CAMERA image"))
        self.pushButton_image_save_series.setText(_translate("XAn", "create and save"))
        self.pushButton_image_browse_multiple_data.setText(_translate("XAn", "browse"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_image_series), _translate("XAn", "image series"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    XAn = QtWidgets.QMainWindow()
    ui = Ui_XAn()
    ui.setupUi(XAn)
    XAn.show()
    sys.exit(app.exec_())

